def on_button_pressed_a():
    global button_a
    button_a = 1
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
    global button_a
    button_a = 0
input.on_button_pressed(Button.B, on_button_pressed_b)

def song_part_2():
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.QUARTER))
    music.play_tone(247, music.beat(BeatFraction.HALF))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    for index in range(2):
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(233, music.beat(BeatFraction.QUARTER))
        music.play_tone(233, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
button_a = 0
button_a = 0
dum_value = 1
led.set_brightness(0)
basic.show_leds("""
    . . . . .
        . # # # .
        # # . # #
        . # # # .
        . . . . .
""")
music.set_tempo(120)
while TobbieII.Read_LBlock() + TobbieII.Read_RBlock() < 50:
    pass
led.set_brightness(255)

def on_forever():
    for index2 in range(2):
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(247, music.beat(BeatFraction.QUARTER))
        music.play_tone(247, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(233, music.beat(BeatFraction.QUARTER))
        music.play_tone(233, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
    for index3 in range(2):
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(1174.66, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(880, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.play_tone(523, music.beat(BeatFraction.QUARTER))
        music.play_tone(523, music.beat(BeatFraction.QUARTER))
        music.play_tone(1174.66, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(880, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.play_tone(494, music.beat(BeatFraction.QUARTER))
        music.play_tone(494, music.beat(BeatFraction.QUARTER))
        music.play_tone(1174.66, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(880, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.play_tone(466, music.beat(BeatFraction.QUARTER))
        music.play_tone(466, music.beat(BeatFraction.QUARTER))
        music.play_tone(1174.66, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(880, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.HALF))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(587, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.HALF))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(831, music.beat(BeatFraction.HALF))
    music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(831, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1046.50, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1174.66, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1174.66, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1174.66, music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.play_tone(1174.66, music.beat(BeatFraction.QUARTER))
    music.play_tone(1046.50, music.beat(BeatFraction.DOUBLE))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(784, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1046.50, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.play_tone(784, music.beat(BeatFraction.HALF))
    music.play_tone(1174.66, music.beat(BeatFraction.HALF))
    music.play_tone(880, music.beat(BeatFraction.HALF))
    music.play_tone(784, music.beat(BeatFraction.HALF))
    music.play_tone(698, music.beat(BeatFraction.HALF))
    music.play_tone(1046.50, music.beat(BeatFraction.HALF))
    music.play_tone(784, music.beat(BeatFraction.HALF))
    music.play_tone(698, music.beat(BeatFraction.HALF))
    music.play_tone(659, music.beat(BeatFraction.HALF))
    music.play_tone(466, music.beat(BeatFraction.HALF))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(932, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1046.50, music.beat(BeatFraction.DOUBLE))
    music.rest(music.beat(BeatFraction.QUARTER))
    for index4 in range(2):
        music.rest(music.beat(BeatFraction.DOUBLE))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(831, music.beat(BeatFraction.EIGHTH))
        music.play_tone(784, music.beat(BeatFraction.EIGHTH))
        music.play_tone(698, music.beat(BeatFraction.EIGHTH))
        music.play_tone(587, music.beat(BeatFraction.EIGHTH))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(784, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(831, music.beat(BeatFraction.HALF))
        music.play_tone(880, music.beat(BeatFraction.QUARTER))
        music.play_tone(1046.50, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(880, music.beat(BeatFraction.QUARTER))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(659, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(784, music.beat(BeatFraction.HALF))
        music.play_tone(880, music.beat(BeatFraction.HALF))
        music.play_tone(1046.50, music.beat(BeatFraction.HALF))
        music.play_tone(1108.73, music.beat(BeatFraction.HALF))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(466, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.WHOLE))
        music.play_tone(587, music.beat(BeatFraction.WHOLE))
        music.play_tone(659, music.beat(BeatFraction.WHOLE))
        music.play_tone(698, music.beat(BeatFraction.WHOLE))
        music.play_tone(784, music.beat(BeatFraction.WHOLE))
        music.play_tone(659, music.beat(BeatFraction.WHOLE))
        music.play_tone(880, music.beat(BeatFraction.WHOLE))
        music.play_tone(880, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(880, music.beat(BeatFraction.QUARTER))
        music.play_tone(831, music.beat(BeatFraction.QUARTER))
        music.play_tone(784, music.beat(BeatFraction.QUARTER))
        music.play_tone(740, music.beat(BeatFraction.QUARTER))
        music.play_tone(698, music.beat(BeatFraction.QUARTER))
        music.play_tone(659, music.beat(BeatFraction.QUARTER))
        music.play_tone(622, music.beat(BeatFraction.QUARTER))
        music.play_tone(587, music.beat(BeatFraction.QUARTER))
        music.play_tone(554, music.beat(BeatFraction.DOUBLE))
        music.play_tone(622, music.beat(BeatFraction.DOUBLE))
    music.play_tone(233, music.beat(BeatFraction.DOUBLE))
    music.play_tone(233, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.DOUBLE))
    music.play_tone(294, music.beat(BeatFraction.DOUBLE))
    music.play_tone(349, music.beat(BeatFraction.BREVE))
    music.play_tone(349, music.beat(BeatFraction.BREVE))
    music.play_tone(233, music.beat(BeatFraction.DOUBLE))
    music.play_tone(233, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.DOUBLE))
    music.play_tone(294, music.beat(BeatFraction.DOUBLE))
    music.play_tone(294, music.beat(BeatFraction.BREVE))
    music.play_tone(294, music.beat(BeatFraction.BREVE))
    music.play_tone(233, music.beat(BeatFraction.DOUBLE))
    music.play_tone(233, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.DOUBLE))
    music.play_tone(294, music.beat(BeatFraction.DOUBLE))
    music.play_tone(349, music.beat(BeatFraction.BREVE))
    music.play_tone(349, music.beat(BeatFraction.BREVE))
    music.play_tone(233, music.beat(BeatFraction.DOUBLE))
    music.play_tone(233, music.beat(BeatFraction.WHOLE))
    music.play_tone(349, music.beat(BeatFraction.WHOLE))
    music.play_tone(330, music.beat(BeatFraction.DOUBLE))
    music.play_tone(294, music.beat(BeatFraction.DOUBLE))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    music.play_tone(1396.91, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1318.51, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(1046.50, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1318.51, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1174.66, music.beat(BeatFraction.HALF))
    music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.play_tone(1046.50, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(1396.91, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1318.51, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(1046.50, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1318.51, music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.play_tone(1174.66, music.beat(BeatFraction.HALF))
    music.play_tone(784, music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.QUARTER))
    music.play_tone(1046.50, music.beat(BeatFraction.QUARTER))
    song_part_2()
basic.forever(on_forever)

def on_forever2():
    if button_a == dum_value:
        TobbieII.stopwalk()
        TobbieII.stopturn()
    else:
        TobbieII.forward()
        while not (button_a == dum_value):
            if TobbieII.rblock(100):
                TobbieII.stopwalk()
                TobbieII.rightward()
                while TobbieII.rblock(60):
                    pass
                basic.pause(200)
                TobbieII.stopturn()
                TobbieII.forward()
            elif TobbieII.lblock(100):
                if True:
                    TobbieII.stopwalk()
                    TobbieII.leftward()
                    while TobbieII.lblock(60):
                        pass
                    basic.pause(200)
                    TobbieII.stopturn()
                    TobbieII.forward()
basic.forever(on_forever2)
